### ISSUE TITLE
Linkify ServiceNow references

### ISSUE THREAD

**Issue by blairconrad** [blairconrad/AgfaJiraChromeExtension#16]
e.g. if `CMTSK0122488` appears in an issue, we could transform it into a link with target 
`https://agfa.service-now.com/textsearch.do?sysparm_search=CMTSK0122488`.

**Comment by blairconrad** [comment]
Would be valid for 

* CMTSKs
* COMs
* PRBs

something else I can't think of?

**Comment by paulsbduncan** [comment]
Oh, that would be nice!  Those are probably all the prefixes we need for
now, but I'll keep a half an eye out for others.

**Comment by blairconrad** [comment]
Thanks for the merge, champ!
Interested in a release? The only thing in our way is the combination of my extreme laziness and the unmerged #15.
