### ISSUE TITLE
Automated deploy fails

### ISSUE THREAD

**Issue by blairconrad** [blairconrad/AgfaJiraChromeExtension#22]
See https://ci.appveyor.com/project/blairconrad/agfajirachromeextension/build/17

**Comment by blairconrad** [comment]
Aha!

Our refresh token probably expired. From https://developers.google.com/identity/protocols/OAuth2#expiration:

>  A refresh token might stop working for one of these reasons:
>
> The user has revoked your app's access.
> The refresh token has not been used for six months.
> …

**Comment by paulsbduncan** [comment]
I'm sure it has been 6 months!

BTW, with dcm4che: 15 seconds.

**Comment by blairconrad** [comment]
I spent over an hour trying to find out a way to generate a refresh token, but it seems all the old ways don't work anymore. Even [How to Continuously Deploy a Chrome Extension](https://circleci.com/blog/continuously-deploy-a-chrome-extension/) from 2017-10-23 no longer appears to work.  I've lost interest in the feature. We release so infrequently, we might as well just do it by hand.
