### ISSUE TITLE
Throw Firefox some love

### ISSUE THREAD

**Issue by MarcBernard** [blairconrad/AgfaJiraChromeExtension#29]
Firefox users would appreciate being able to use this too.

**Comment by blairconrad** [comment]
I welcome your PR!

Or at the very least hints about how to adapt for Firefox. What do you know? I haven't written a Firefox extension since they were called Greasemonkey.

**Comment by MarcBernard** [comment]
I think it's just a case of mucking with the manifest, and maybe de-googling some of the code. I can take a crack at it in my spare time.
